inherit_gem:
  rubocop-fjord:
    - config/rubocop.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - test/**/*

Rails/SkipsModelValidations:
  Exclude:
    - app/models/rank.rb

Style/ClassVars:
  Exclude:
    - app/models/bot.rb

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
